name: MerlyMentor
on:
    push:
      branches: [ "main","master" ]
    pull_request:
      branches: [ "main","master" ]

env:
    MM_Install: ../../MM-Install
    MM_KEY: ${{ secrets.MM_KEY }}

jobs:
    inference:
         runs-on: ubuntu-latest
         
         steps:
         - uses: actions/checkout@v3
           with:
              fetch-depth: ’0’
          
         - name: install MerlyMentor
           run: |
                echo "::add-mask::${{ secrets.MM_KEY }}"
                mkdir "$MM_Install"
                cd "$MM_Install"
                  curl -fsSL https://raw.githubusercontent.com/merly-ai/MPCC-Universal/main/install.sh | bash -s -- -q -k "$MM_KEY" install --staging
          
         - name: Run MerlyMentor
           run: |
              echo "::add-mask::${{ secrets.MM_KEY }}"
              cd "$MM_Install"
              ./MerlyMentor-Staging --github-actions -D ${{github.workspace}}/ -r MerlyMentor check
